name: Sync Docker Hub Description
on:
  push:
    paths:
      - 'README.md'
jobs:
  build:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker Hub Description
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPO: ${{ github.repository }}
        run: |
          README_CONTENT=$(cat README.md | sed 's/"/\\"/g')
          
          JSON_PAYLOAD=$(cat <<EOF
          {
            "full_description": "$README_CONTENT"
          }
          EOF
          )

          curl -s -u "$DOCKERHUB_USERNAME:$DOCKERHUB_PASSWORD" \
            -X PATCH "https://hub.docker.com/v2/repositories/$DOCKERHUB_REPO/" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
